### ISSUE TITLE
Regions are Defined but disapear

### ISSUE THREAD

**Issue by imjack** [fromgate/Regions#1]
Once a region is created and the server is restarted /rg info shows there is no region around me although it was just defined before the server restart.

**Comment by imjack** [comment]
I think it is possibly caused by capitals letters in world names.

After doing some debugging It looks like in the Area class Line 43 toLowerCase causes this problem.

**Comment by fromgate** [comment]
Thank you!
I hope this help. All my worlds was created in lower case :)
